@echo off
echo [93mЗагрузка последней версии...
echo;
echo [93m Скачивание утилиты для управления репозиторием c github...
certutil -urlcache -split -f "https://github.com/lisikme/GoodbyeDPI-Mod-KR.Corp/raw/main/srv/Unlocker.exe" C:\Windows\Temp\unlocker.exe > nul
echo [93m Скачивание репозитория c github...
certutil -urlcache -split -f "https://github.com/lisikme/GoodbyeDPI-Mod-KR.Corp/archive/refs/heads/main.zip" C:\Windows\Temp\goodtemp.zip > nul
echo [93m распаковка архива...
powershell Expand-Archive -Path C:\Windows\Temp\goodtemp.zip -DestinationPath C:\Windows\Temp\ -Force
echo [93m Компеляция утилиты...
powershell Move-Item -LiteralPath 'C:\Windows\Temp\GoodbyeDPI-Mod-KR.Corp-main' -Destination 'C:\goodbyedpi' -Force
echo [93m Открытие утилиты...
powershell Start-Process -FilePath "C:\goodbyedpi\Installer.cmd" > nul
start C:\Windows\Temp\unlocker.exe "C:\Windows\Temp\goodtemp.zip" 
pause 